[project]
name = "m3u-file-generator"
version = "0.1.0"
description = "Downloads M3U playlists from a given URI (scraping), then generates one that contains working links to both channels and VOD links based on defined criteria"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.124.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
